### ISSUE TITLE
init添加一个npm库模板？

### ISSUE THREAD

**Issue by xubillde** [wytxer/docs-web-infrastructure#1]

**Comment by wytxer** [comment]
你是指生成一个 package.json 模板文件，里面包含了比较全的字段？

**Comment by wytxer** [comment]
你是指生成一个 package.json 模板文件，里面包含了比较全的字段？

**Comment by xubillde** [comment]
生成一个新的npm发布库

**Comment by wytxer** [comment]
抱歉最近比较忙没能及时回复。你说的这个 npm 发布库，是针对什么场景的呢？我还是不太明白你说的意思
